# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-13 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('url_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='url唯一标识')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='小说链接')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='小说图片')),
                ('image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='小说图片路径')),
                ('site_name', models.CharField(max_length=32, verbose_name='网站名称')),
                ('novel_name', models.CharField(max_length=64, unique=True, verbose_name='小说名称')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'tb_novel',
            },
        ),
        migrations.CreateModel(
            name='NovelAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='作者名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'tb_novel_author',
            },
        ),
        migrations.CreateModel(
            name='NovelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='小说分类')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'tb_novel_category',
            },
        ),
        migrations.AddField(
            model_name='novel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.NovelAuthor', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='novel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.NovelCategory', verbose_name='分类'),
        ),
    ]
